#include <iostream>
using namespace std;

/**
 * A function to determine the length of a string in bytes, where a c++ string is a char array type pointer that ends with \0
 * @param str   the string chararray to be used
 * @returns The length of the string
 */
unsigned int length(const char* str)
{
    // assume length 0
    unsigned int length = 0;
    // this assumes that the character array hasn't been manipulated to remove a terminating \0
    // '\0' resolves as false
    while(*str)
    {
        // increase the length integer
        length++;
        // move the pointer forward
        str++;
    }
    
    return length;
}

// this should be true
bool length_test_case_1()
{
    return (length("") == 0);
}

// this should be true
bool length_test_case_2()
{
    return (length("test") == 4);
}

// this should be true
bool length_test_case_3()
{
    return (length("this is an arbitrarily long test case") == 37);
}

// this should be true
bool length_test_case_4()
{
    return length("\0") == 0;
}

// this should be false because unicode characters are two bytes and a char is one byte
bool length_test_case_5()
{
    
    return length("éxtrá?")==6;
}

// this should be true
bool length_test_case_6()
{
    
    return length("éxtrá?")==8;
}

/**
 * I am assuming for the point of this question that we're not supposed to just
 * while ((*src++ = *from++)!='\0') which works.
 * Having spoken with Hao about this in lecture, we can disregard the NULL requirement
 * and just assume that there is sufficient space because "size" is not a meaningful keyword
 * in terms of a pointer, it will always just be the size of the type.
 */
char* copy(char* src, const char* test)
{
    int len2 = length(test);
    // treating the char pointers as arrays for simplicity of reading and comprehension
    for(int i = 0; i < len2; i++)
    {
        src[i] = test[i];
    }
    // making sure to add a terminator to the end
    src[len2] = '\0';
    return src;
}

/**
 * A quick method to compare two strings, we use this in a bunch of places
 */
bool strMatch(const char* str1, const char* str2)
{
    int strLen1 = length(str1);
    if(strLen1 != length(str2))
    {
        // if they're different lengths, they can't be the same strings
        return false;
    }

    for(int i = 0; i < strLen1; i++)
    {
        if(*str1 != *str2)
        {
            // if, at any point, the characters disagree, it's not the same string
            return false;
        }
        str1++;
        str2++;
    }
    // but we get here, so it is.
    return true;
}

/**
 */
bool copy_test_case_1()
{
    const char* test = "This is a test";
    char testCopy[100];
    copy(testCopy, test);
    bool result = strMatch(testCopy, test);    
    return result;
}


/**
 * This more or less replicates length's functionality but as a side effect.
 * Length could be implemented as an function that opaquely maps length(str) to indexOf('\0', str)
 */
int indexOf(char c, const char* str)
{
    bool lfc = c == '\0';
    int i = 0;
    while((*str != '\0'))
    {
        if(*str == c)
        {
            return i;
        }
        str++;
        i++; 
    }

    return lfc?i:-1;
}

bool indexOf_test_case_1()
{
    return indexOf('a', "this is a test") == 8;
}

bool indexOf_test_case_2()
{
    return indexOf('a', "this should return -1") == -1;
}

bool indexOf_test_case_3()
{
    return length("this is a test") == indexOf('\0', "this is a test");
}


/**
 * Generates a substring of a given string between the bounds i and j
 * @param str   The string to get a subset of
 * @param i     The start offset of the substring
 * @param j     The end offset of the substr
 * @return      The substring generated by this method
 */
char* substring (int i, int j, const char* str)
{
    // get the length of the strgin
    int len = length(str);
    // make sure i and j are within bounds
    if(i < 0 || j > len || i >= j)
    {
        return nullptr;
    }
    
    // ignore the first i characters
    for(int c = 0; c < i; c++)
    {
        str++;
    }

    // figure out how long the character array needs to be
    const int subStrLen = j - i;
    
    // declare and initialise said array
    char* out = new char[subStrLen + 1];

    // populate it
    for(int c = 0; c < subStrLen; c++)
    {
        out[c] = *str++;
    }

    // add the terminator
    out [subStrLen] = '\0';

    // return it
    return out;
}

bool substring_test_case_1()
{
    const char* thisWord = "this";
    char* subStr = substring(0, 4, "this is a string");
    bool match =  strMatch(subStr, thisWord);
    delete[] subStr;
    return match;
}

bool substring_test_case_2()
{
    char* thisWord = "is";
    char* subStr = substring(2, 4, "this is a string");
    bool match =  strMatch(subStr, thisWord);
    delete[] subStr;
    return match;
}

bool substring_test_case_3()
{
    char* subStr = substring(5, 3, "this is a string");
    bool match = subStr == nullptr;
    delete[] subStr;
    return match;
}

bool substring_test_case_4()
{
    char* sub = substring(-4, 2, "this is a string");
    bool match = sub == nullptr;
    delete[] sub;
    return match;
}

bool substring_test_case_5()
{
    char* subStr = substring(5, 53, "this is a string");
    bool match = subStr == nullptr;
    delete[] subStr;
    return match;
}

/**
 * I am intentionally disregarding utf characters here because they're a nuisance to deal with in terms of replacement in this context.
 */
char* replace(char c, char p, const char* str)
{
    int len = length(str);// this provides an absolute upper bound for size of the output string
    char* out = new char[len];
    
    for(int i = 0; i < len; i++)
    {
        out[i] = *str == c?p:*str;
        *str++;
    }
    out[len] = '\0';
    return out;
}

bool replace_test_case_1()
{
    char* replaced = replace('e', 'o', "test");
    bool matches = strMatch(replaced, "tost");
    delete replaced;
    return matches;
}

bool replace_test_case_2()
{
    char* replaced = replace('e', 'e', "test");
    bool matches = strMatch(replaced, "test");
    delete replaced;
    return matches;
}

bool replace_test_case_3()
{
    char* replaced = replace('a', 'e', "test");
    bool matches = strMatch(replaced, "test");
    delete replaced;
    return matches;
}

int main()
{
    cout << length_test_case_1() <<endl;
    cout << length_test_case_2() <<endl;
    cout << length_test_case_3() <<endl;
    cout << length_test_case_4() <<endl;
    cout << length_test_case_5() <<endl;
    cout << length_test_case_6() <<endl;
    
    cout << copy_test_case_1() <<endl;

    cout << indexOf_test_case_1() <<endl;
    cout << indexOf_test_case_2() <<endl;
    cout << indexOf_test_case_3() <<endl;

    cout << substring_test_case_1() << endl;
    cout << substring_test_case_2() << endl;
    cout << substring_test_case_3() << endl;
    cout << substring_test_case_4() << endl;
    cout << substring_test_case_5() << endl;
    
    cout << replace_test_case_1() << endl;
    cout << replace_test_case_2() << endl;
    cout << replace_test_case_3() << endl;

    return 0;
}
